use crate::ZipInspection;
use std::collections::BTreeMap;
use std::fmt;
use std::path::Path;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EditionProfile { pub schema_version: u32, pub id: String, pub edition_name: String, pub region: String, pub input_sha256: String, pub input_size: u64, pub installer_type: String, pub extraction_method: String, pub installer_path: String, pub installer_sha256: String, pub data_path: String, pub data_sha256: String, pub data_size: u64, pub enabled: bool, pub required_zip_paths: Vec<String> }
impl EditionProfile { pub fn matches(&self, zip: &ZipInspection) -> bool { zip.size == self.input_size && self.input_sha256.eq_ignore_ascii_case(&zip.sha256) && !zip.entries.iter().any(|entry| entry.encrypted) && self.required_zip_paths.iter().all(|path| zip.entries.iter().any(|entry| &entry.path == path)) } }
#[derive(Debug, Clone)] pub struct ProfileError(pub String); impl fmt::Display for ProfileError { fn fmt(&self,f:&mut fmt::Formatter<'_>)->fmt::Result {f.write_str(&self.0)} } impl std::error::Error for ProfileError {}

pub fn load_profiles(dir: &Path) -> Result<Vec<EditionProfile>, ProfileError> { let mut result=Vec::new(); let entries=std::fs::read_dir(dir).map_err(|e|ProfileError(format!("Cannot read profiles: {e}")))?; for entry in entries { let entry=entry.map_err(|e|ProfileError(e.to_string()))?; if entry.path().extension().is_some_and(|extension| extension=="toml") { result.push(parse_profile(&std::fs::read_to_string(entry.path()).map_err(|e|ProfileError(e.to_string()))?)?); } } if result.is_empty() { return Err(ProfileError("No edition profiles were found.".into())); } Ok(result) }
pub fn parse_profile(input: &str) -> Result<EditionProfile, ProfileError> { let mut values=BTreeMap::new(); let mut required_zip_paths=Vec::new(); for (number,line) in input.lines().enumerate() { let line=line.split('#').next().unwrap_or("").trim(); if line.is_empty() {continue} let (key,value)=line.split_once('=').ok_or_else(||ProfileError(format!("line {} is not key = value",number+1)))?; let key=key.trim(); let value=value.trim().trim_matches('"'); if key=="required_zip_path" { required_zip_paths.push(value.into()); } else { values.insert(key.to_owned(),value.to_owned()); } } let required=|key:&str|values.get(key).cloned().ok_or_else(||ProfileError(format!("missing required profile key {key}"))); let number=|key:&str|required(key)?.parse::<u64>().map_err(|_|ProfileError(format!("{key} must be an unsigned integer"))); let schema=required("schema_version")?.parse::<u32>().map_err(|_|ProfileError("schema_version must be a u32".into()))?; if schema != 1 { return Err(ProfileError(format!("unsupported profile schema {schema}"))); } for path in [&required("installer_path")?, &required("data_path")?] { crate::safe_relative_path(Path::new(path)).map_err(|_|ProfileError("installer paths must be safe relative paths".into()))?; } Ok(EditionProfile { schema_version:schema,id:required("id")?,edition_name:required("edition_name")?,region:required("region")?,input_sha256:required("input_sha256")?,input_size:number("input_size")?,installer_type:required("installer_type")?,extraction_method:required("extraction_method")?,installer_path:required("installer_path")?,installer_sha256:required("installer_sha256")?,data_path:required("data_path")?,data_sha256:required("data_sha256")?,data_size:number("data_size")?,enabled:required("enabled")?=="true",required_zip_paths }) }
#[cfg(test)] mod tests { use super::*; #[test] fn rejects_unsafe_installer_path() { assert!(parse_profile("schema_version = 1\nid = \"x\"\nedition_name = \"x\"\nregion = \"x\"\ninput_sha256 = \"x\"\ninput_size = 1\ninstaller_type = \"x\"\nextraction_method = \"x\"\ninstaller_path = \"../x\"\ninstaller_sha256 = \"x\"\ndata_path = \"x\"\ndata_sha256 = \"x\"\ndata_size = 1\nenabled = false").is_err()); }
#[test] fn requires_every_profiled_zip_member_and_rejects_encryption() { let profile=parse_profile("schema_version=1\nid=x\nedition_name=x\nregion=x\ninput_sha256=hash\ninput_size=9\ninstaller_type=x\nextraction_method=x\ninstaller_path=a/setup.exe\ninstaller_sha256=x\ndata_path=a/setup-1.bin\ndata_sha256=x\ndata_size=2\nenabled=true\nrequired_zip_path=a/setup.exe\nrequired_zip_path=a/setup-1.bin").unwrap(); let plain=ZipInspection{sha256:"hash".into(),size:9,entries:vec![crate::ZipEntry{path:"a/setup.exe".into(),size:1,encrypted:false},crate::ZipEntry{path:"a/setup-1.bin".into(),size:2,encrypted:false}]}; assert!(profile.matches(&plain)); let missing=ZipInspection{entries:vec![plain.entries[0].clone()],..plain.clone()}; assert!(!profile.matches(&missing)); let encrypted=ZipInspection{entries:vec![crate::ZipEntry{path:"a/setup.exe".into(),size:1,encrypted:true},plain.entries[1].clone()],..plain}; assert!(!profile.matches(&encrypted)); } }
